# Site
title:              Jai Gupta
bio:                'Cyber Security Enthusiast. Always hungry to keep learning'
description:        "Cyber Security Enthusiast. Always hungry to keep learning"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaiguptanick.github.io/Blog" # the base hostname & protocol for your site

# Comments
disqus_shortname: https-jaiguptanick-github-io-jazz-blog

# Social
analytics-id:       "UA-162845146-1"
twitter:            jaiguptanick
facebook:           jaiguptanick
instagram:          jaigupta_nick
github:             jaiguptanick

# personal
location:           Dhanbad,Jharkhand,India
phone:              9793295951
email:              jaiguptanick@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Jai Gupta

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
